# Generated by Django 4.2.4 on 2023-10-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('pessoa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('turno', models.CharField(blank=True, max_length=1, null=True)),
                ('datacadastro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pessoas',
            },
        ),
    ]
