# Generated by Django 4.2.4 on 2023-09-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Silo',
            fields=[
                ('silo_id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'silos',
            },
        ),
    ]
