# Generated by Django 4.2.4 on 2023-09-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silo',
            name='descricao',
        ),
        migrations.AddField(
            model_name='silo',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
