# Generated by Django 4.2.4 on 2023-09-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cpfcnpj', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
