# Generated by Django 4.2.4 on 2023-10-01 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0002_rename_cpfcnjp_empresa_cpfcnpj'),
        ('operador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descarregamento',
            fields=[
                ('descarregameto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(blank=True, max_length=15, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('veiculo_limpo', models.CharField(blank=True, max_length=1, null=True)),
                ('qtd_citrato', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('qtd_fosfato', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('inicio_descarga', models.DateTimeField(blank=True, null=True)),
                ('fim_descarga', models.DateTimeField(blank=True, null=True)),
                ('qtd_litros_nota', models.IntegerField(blank=True, null=True)),
                ('qtd_litros_bomba', models.IntegerField(blank=True, null=True)),
                ('situacao', models.CharField(blank=True, max_length=25, null=True)),
                ('empresa_id', models.ForeignKey(blank=True, db_column='empresa_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.empresa')),
                ('operadoestabilizacao_id', models.ForeignKey(blank=True, db_column='operadoestabilizacao_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operador.pessoa')),
                ('operadorcoleta_id', models.ForeignKey(blank=True, db_column='operadorcoleta_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operadorcoleta_id', to='operador.pessoa')),
                ('operadorlimpeza_id', models.ForeignKey(blank=True, db_column='operadorlimpeza_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operadorlimpeza_id', to='operador.pessoa')),
            ],
            options={
                'db_table': 'descarregamentos',
            },
        ),
    ]
