# Generated by Django 4.2.4 on 2023-10-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descarregamento', '0002_descarregamento_diferenca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descarregamento',
            name='situacao',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
