# Generated by Django 4.2.4 on 2023-10-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descarregamento', '0003_alter_descarregamento_situacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descarregamento',
            old_name='fim_descarga',
            new_name='horario_fim_descarga',
        ),
        migrations.RenameField(
            model_name='descarregamento',
            old_name='inicio_descarga',
            new_name='horario_inicio_descarga',
        ),
        migrations.AddField(
            model_name='descarregamento',
            name='horario_coleta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarregamento',
            name='horatio_saida_veiculo',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarregamento',
            name='lote_citrato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='descarregamento',
            name='lote_fosfato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='descarregamento',
            name='primeiro_recipiente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarregamento',
            name='segundo_recipiente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarregamento',
            name='temp_primeiro_recipiente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarregamento',
            name='temp_segundo_recipiente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarregamento',
            name='temp_terceiro_recipiente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarregamento',
            name='terceiro_recipiente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
