# Generated by Django 4.2.4 on 2023-10-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descarregamento', '0004_rename_fim_descarga_descarregamento_horario_fim_descarga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descarregamento',
            name='horario_fim_descarga',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descarregamento',
            name='horario_inicio_descarga',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
