# Generated by Django 4.2.4 on 2023-10-21 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descarregamento', '0005_alter_descarregamento_horario_fim_descarga_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descarregamento',
            old_name='horatio_saida_veiculo',
            new_name='horario_saida_veiculo',
        ),
    ]
